name: CI  
  
on:  
  push:  
    branches: [ master ]  
  pull_request:  
    branches: [ master ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
      - uses: actions/checkout@v2  
  
      # 设置Java环境  
      - name: Set up JDK 11  
        uses: actions/setup-java@v2  
        with:  
          java-version: '11'  
          distribution: 'adopt'  
  
      # 缓存Maven依赖以加快构建速度  
      - name: Cache Maven packages  
        uses: actions/cache@v2  
        with:  
          path: ~/.m2  
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}  
          restore-keys: ${{ runner.os }}-m2  
  
      # 构建项目并跳过测试  
      - name: Build with Maven  
        run: mvn clean package -DskipTests -Dmaven.javadoc.skip=true  
  
      # 使用Checkstyle进行代码风格检查  
      - name: Run Checkstyle  
        run: mvn checkstyle:check  
  
      # 使用SpotBugs进行静态代码分析  
      - name: Run SpotBugs  
        run: mvn spotbugs:check  
  
      # （可选）将检查结果作为注释添加到Pull Request  
      # ...  
  
      # （可选）将构建产物作为Artifacts保存  
      - name: Upload artifacts  
        uses: actions/upload-artifact@v2  
        with:  
          name: artifacts  
          path: target/*.jar
