name: Java Code Check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Run Maven build
        run: mvn clean verify

      - name: Check code style
        uses: github/super-linter@v3
        with:
          repo-token: ${{ github.token }}
          enabled-linters: 'java'
