name: Code Quality Check

on:
  push:
    branches:
      - master

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install maven -y

    - name: Build and analyze code
      run: |
        mvn clean install -DskipTests
        mvn pmd:pmd -DskipTests
        mvn checkstyle:checkstyle -DskipTests
